name: Merge Staging to Main

on:
  push:
    branches:
      - staging

jobs:
  merge_to_master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - run: |
          cat README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/staging --no-ff --no-edit
          git push origin
