name: Merge Staging to Main

on:
  push:
    branches:
      - staging

jobs:
  merge_to_master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge staging into Main
        run: |
          git fetch
          git checkout main
          git merge origin/staging --no-ff --no-edit
          git push origin
