name: Merge Staging to Master

on:
  push:
    branches:
      - staging

jobs:
  merge_to_master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge staging into master
        run: |
          git checkout master
          git merge staging --no-ff --no-edit
          git push origin master
